csis3600/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.CreateContact.as_view(), name='contactForm'),
    path('thank-you-now-get-out-of-here/',
         views.Success.as_view(), name='success'),
]

handler404 = 'csis3600.views.handler404'
handler500 = 'csis3600.views.handler500'

csis3600/csis3600/urls.py
from django.contrib import admin
from django.urls import path, include
from myWebsite import views as workViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', workViews.Week12.as_view(), name='home'),
    path('weeklywork/', include('myWebsite.urls', namespace='weeklywork')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('secret/', include('secret.urls', namespace='secret')),
]

csis3600/myWebsite/urls.py
from django.urls import path
from . import views

app_name = 'myWebsite'

urlpatterns = [
    path('week-1/', views.Week1.as_view(), name='week1'),
    path('week-2/', views.Week2.as_view(), name='week2'),
    path('week-3/', views.Week3.as_view(), name='week3'),
    path('week-4/', views.Week4.as_view(), name='week4'),
    path('week-5/', views.Week5.as_view(), name='week5'),
    path('week-6/', views.Week6.as_view(), name='week6'),
    path('week-7/', views.Week7.as_view(), name='week7'),
    path('week-8/', views.Week8.as_view(), name='week8'),
    path('week-12/', views.Week12.as_view(), name='week12'),
    path('week-13/', views.Week13.as_view(), name='week13'),
]

handler404 = 'csis3600.views.handler404'
handler500 = 'csis3600.views.handler500'

csis3600/secret/urls.py
from django.urls import path
from . import views


app_name = 'secret'

urlpatterns = [
    path('', views.FirstClueView.as_view(), name='clue1'),
]


handler404 = 'csis3600.views.handler404'
handler500 = 'csis3600.views.handler500'

csis3600/contact/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Contact(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=50)
    comments = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.first_name + ' - ' + '"' + self.comments + '"'

    def get_absolute_url(self):
        return reverse('contact:success')

csis3600/myWebsite/models.py
from django.db import models

csis3600/secret/models.py
from django.db import models

# Create your models here.

csis3600/contact/views.py
from django.views.generic import CreateView, TemplateView
from .models import Contact


class CreateContact(CreateView):
    model = Contact
    fields = ['first_name', 'last_name', 'email', 'comments']


class Success(TemplateView):
    template_name = 'contact/success.html'

csis3600/csis3600/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext


def handler404(request, exception, template_name='404.html'):
    response = render_to_response('404.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {}, context_instance=RequestContext(request))
    response.status_code = 500
    return response

csis3600/myWebsite/views.py
from django.views.generic.base import TemplateView


class Week1(TemplateView):
    template_name = 'myWebsite/week1.html'


class Week2(TemplateView):
    template_name = 'myWebsite/week2.html'


class Week3(TemplateView):
    template_name = 'myWebsite/week3.html'


class Week4(TemplateView):
    template_name = 'myWebsite/week4.html'


class Week5(TemplateView):
    template_name = 'myWebsite/week5.html'


class Week6(TemplateView):
    template_name = 'myWebsite/week6.html'


class Week7(TemplateView):
    template_name = 'myWebsite/week7.html'


class Week8(TemplateView):
    template_name = 'myWebsite/week8.html'

class Week12(TemplateView):
    template_name = 'myWebsite/week12.html'

class Week13(TemplateView):
    template_name = 'myWebsite/week13.html'

csis3600/secret/views.py
from django.views.generic import TemplateView

# Create your views here.


class FirstClueView(TemplateView):
    template_name = 'secret/clue1.html'

csis3600/contact/templates/contact/contact_form.html
{% extends "base.html" %}
{% block title %}
  <title>Contact Me | CSIS 3600 | Spring 2018</title>
{% endblock %}
{% block body %}
<div class="homework-container">
  <div class="title-container">
    <h2><i class="fal fa-book fa-xs"></i> Contact Me</h2>
  </div>
  <div class="homework">
    <form class="form-grid" action="{% url 'contact:contactForm' %}" method="post">
      {% csrf_token %}
      {{ form }}
      <button type="submit">Send It</button>
    </form>
  </div>
</div>
{% endblock %}

csis3600/contact/templates/contact/success.html
{% extends "base.html" %}
{% block title %}
  <title>Thank You | CSIS 3600 | Spring 2018</title>
{% endblock %}
{% block body %}
<div class="homework-container">
  <div class="title-container">
    <h2><i class="fal fa-book fa-xs"></i> You have contacted me..</h2>
  </div>
    <div class="error-container">
      <h2>Thank You! I probably won't get back to you. <i class="fal fa-thumbs-up"></i></h2>
      <a href="{% url 'home' %}">Back To Home</a>
    </div>
</div>
{% endblock %}

csis3600/myWebsite/templates/myWebsite/week1.html
{% extends "base.html" %} {% block title %}
<title>Week 1 | CSIS 3600 | Spring 2018</title>
{% endblock %} {% block body %}
<div class="homework-container">
  <div class="title-container">
    <h2><i class="fal fa-book fa-xs"></i> Week 1</h2>
  </div>
  <div class="homework justify-text">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 1. List 20 different application that appear in the ftype command</h3>
    <ol>
      <li><span>MSASCUI.exe</span>a process belonging to Microsoft Windows Defender Antispyware which protects your computer against Internet-bound threats</li>
      <li><span>notepad.exe</span>is the executable for Notepad</li>
      <li><span>wpnpinst.exe</span>is a process associated with Microsoft® Windows®</li>
      <li><span>sdclt.exe</span>belonging to Betriebssystem Microsoft® Windows®</li>
      <li><span>wab.exe</span>(Windows Address Book) is a part of the Windows Operating system</li>
      <li><span>WScript.exe</span>is a process relating to Microsoft Windows operating system which allows additional functions to scripting</li>
      <li><span>photoviewer.dll</span>a PhotoViewer belonging to Microsoft® Windows®</li>
      <li><span>regedit.exe</span>is the executable for the Windows Registry Editor</li>
      <li><span>msrating.dll</span>is a module used by the Microsoft Internet Ratings and Local User Management</li>
      <li><span>MSPUP.exe</span>is the main process belonging to Microsoft Publisher</li>
    </ol>
    <ol start="11" class="add-margin">
      <li><span>VirtualBox.exe</span>a process for VirtualBox</li>
      <li><span>pageant.exe</span>is a Pageant belonging to PuTTY suite from Simon Tatham</li>
      <li><span>powerpnt.exe</span>is the main process belonging to Microsoft Publisher product, which allows the production of commercial and personal slideshows</li>
      <li><span>rasphone.exe</span>is a rasphone.exe belonging to Sistema operativo Microsoft® Windows® from Microsoft Corporation</li>
      <li><span>PacketTracer7.exe</span>Cisco networking academy's packet tracer</li>
      <li><span>cryptext.dll</span>is a module associated with Crypto Shell Extensions from Microsoft Corporation</li>
      <li><span>Outlook.exe</span>is the main process belonging to Microsoft Publisher product, which allows the production of commercial and personal emails</li>
      <li><span>MySQLWorkbench.exe</span>process for MySQL Workbench</li>
      <li><span>Kleopatra.exe</span>a process for Kleopatra</li>
      <li><span>dfshim.dll</span>is a module associated with Microsoft® .NET Framework from Microsoft Corporation</li>
    </ol>
  </div>
  <div class="homework">
    <h3><i class="fal fa-pencil"></i> 3. List the Linux commands we convered today and what they do.</h3>
    <ul>
      <li><code>cd</code>
        <p>Change Directory</p>
      </li>
      <li><code>pwd</code>
        <p>See the present working directory</p>
      </li>
      <li><code>ls -al # Or any other variation</code>
        <p>Gives the long listing of the designated directory</p>
      </li>
      <li><code>echo "hello world!" > hello.txt</code>
        <p>Redirects the output "Hello World!" to the file hello.txt</p>
      </li>
      <li><code>echo "Zebra" >> hello.txt</code>
        <p>Appends the output to hello.txt</p>
      </li>
      <li><code>cat hello.txt</code>
        <p>Prints the contents of hello.txt</p>
      </li>
      <li><code>cat /etc/passwd</code>
        <p>Prints the users on the machine</p>
      </li>
    </ul>
    <ul>
      <li><code>rm ~/hello.txt</code>
        <p>Removes hello.txt</p>
      </li>
      <li><code>man ls</code>
        <p>Look at the manual pages for ls</p>
      </li>
      <li><code>cat /etc/passwd | less</code>
        <p>print /etc/passwd and send the output to less</p>
      </li>
      <li><code>tail /etc/passwd</code>
        <p>Prints the last lines of /etc/passwd</p>
      </li>
      <li><code>history</code>
        <p>Prints out the history</p>
      </li>
      <li><code>alias ll='ls -al'</code>
        <p>Sets the specified alias</p>
      </li>
      <li><code>source ~/.bashrc</code>
        <p>Reloads the bash shell</p>
      </li>
    </ul>
  </div>
  <div class="homework">
    <h3><span class="fal fa-pencil"></span> 4. Print the calender for 1752. How far backwards or forwards does the cal program work?</h3>
    <ul>
      <li><code>cal 1752</code></li>
      <li>2 weeks are missing in September</li>
      <li>The program's years range from 1 to 9999</li>
    </ul>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><span class="fal fa-pencil"></span> 5. Pick 10 DOS commands</h3>
    <ol>
      <li><code class="windows-code">tree</code> Graphically displays the directory structure of a drive or path.</li>
      <li><code class="windows-code">shutdown -s</code> Allows proper local or remote shutdown of the machine.</li>
      <li><code class="windows-code">copy</code> Copies one or more files to another location.</li>
      <li><code class="windows-code">chdir</code> Displays the name of of changes the current directory.</li>
      <li><code class="windows-code">cls</code> Clears the screen.</li>
    </ol>
    <ol start="6">
      <li><code class="windows-code">echo hello</code> Displays messages, or turns command echoing on or off.</li>
      <li><code class="windows-code">set</code> Displays, sets, or removes windows environment variables.</li>
      <li><code class="windows-code">tasklist</code> Kill or stop a running tasks including services.</li>
      <li><code class="windows-code">type</code> Displays the contents of a text file.</li>
      <li><code class="windows-code">pushd</code> Saves the current directory then changes it.</li>
    </ol>
  </div>
</div>
{% endblock %}

csis3600/myWebsite/templates/myWebsite/week12.html
{% extends "base.html" %} {% block title %}
<title>Week 12 | CSIS 3600 | Spring 2018</title>
{% endblock %} {% block body %} {% load static %}
<div class="homework-container">
  <div class="title-container">
    <h2><i class="fal fa-book fa-xs"></i> Week 12</h2>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 1. Archive your entire home folder (call it yourname-home.tar)</h3>
    <img src="{% static 'img/week12/1.png' %}" alt="Tar home directory">
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 2. Archive and compress your entire home folder.</h3>
    <img src="{% static 'img/week12/2.png' %}" alt="Tar and compress home directory">
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 3. List the contents of your archive</h3>
    <img src="{% static 'img/week12/3.png' %}" alt="Listing contents of tar file">
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 4. Add grep highlighting to your .bashrc file</h3>
    <img src="{% static 'img/week12/4.png' %}" alt="grep highlighting">
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 5. Look for the pattern "language" in regular expressions.txt.</h3>
    <img src="{% static 'img/week12/5.png' %}" alt="grep language">
    <img src="{% static 'img/week12/5b.png' %}" alt="grep language wordcount">
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 6. Write a script that does the following.</h3>
    <ol type="A">
      <li><img src="{% static 'img/week12/6a.png' %}" alt="/etc/hosts"></li>
      <li><img src="{% static 'img/week12/6b.png' %}" alt="/usr/share/doc"></li>
      <li><img src="{% static 'img/week12/6c.png' %}" alt="/etc/fstab"></li>
      <li><img src="{% static 'img/week12/6d.png' %}" alt="/etc/passwd"></li>
    </ol>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 7. Fix awk01 so it gives exactly the same results as wc.</h3>
    <img src="{% static 'img/week12/7.png' %}" alt="awk01 fix">
  </div>
</div>
{% endblock %}

csis3600/myWebsite/templates/myWebsite/week13.html
{% extends "base.html" %} {% block title %}
<title>Week 13 | CSIS 3600 | Spring 2018</title>
{% endblock %} {% block body %} {% load static %}
<div class="homework-container">
  <div class="title-container">
    <h2><i class="fal fa-book fa-xs"></i> Week 13</h2>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 1. Using the Elements.cvs file, display fields for Names, Symbols, Atomic Number and Discoverer.</h3>
    <div>
      <p>Process:</p>
      <ul>
        <li><code>tr ',' ' ' < Elements.csv > elements2</code></li>
        <li><code>tr -d '\"' < elements2 > elements3</code></li>
        <li><code>awk '(NF != 10) {print $0}' elements3</code></li>
      </ul>
      <img src="{% static 'img/week13/1.png' %}" alt="Elements CSV">
    </div>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 2. The shell uses esac to terminate case and fi to terminate if. Why does it use done to terminate do?</h3>
    <p>Because `od` is already a command which dump files in octal and other formats. Thus `done` had to be used instead.</p>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 3. Write a script that asks the user to enter their name, address, phone number and email.</h3>
    <div>
      <img src="{% static 'img/week13/3.png' %}" alt="User Input Script">
      <img src="{% static 'img/week13/3-2.png' %}" alt="Output">
    </div>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 4. Improve our text2html to allow the user to give a name to the html file then launch a browser to view it in.</h3>
    <div>
      <img src="{% static 'img/week13/4.png' %}" alt="Script">
      <img src="{% static 'img/week13/4-1.png' %}" alt="Terminal">
      <img src="{% static 'img/week13/4-2.png' %}" alt="Firefox output">
    </div>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 5. Write a script called "inventory"</h3>
    <div>
      <img src="{% static 'img/week13/5.png' %}" alt="Script 5">
      <img src="{% static 'img/week13/5-1.png' %}" alt="Terminal 5">
      <img src="{% static 'img/week13/5-2.png' %}" alt="Firefox output 5">
    </div>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 6. Write a script called kill process</h3>
    <div>
      <img src="{% static 'img/week13/6.png' %}" alt="Script 6">
    </div>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 7. What is the maximum number of processes you can kill?</h3>
    <div>
      <img src="{% static 'img/week13/7.png' %}" alt="Terminal">
    </div>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 8. Write a script that will check for a given app every 10 seconds and terminate it.</h3>
    <div>
      <img src="{% static 'img/week13/8-1.png' %}" alt="Script 2">
      <img src="{% static 'img/week13/8-2.png' %}" alt="Firefox output2">
    </div>
  </div>
</div>
{% endblock %}

csis3600/myWebsite/templates/myWebsite/week2.html
{% extends "base.html" %} {% block title %}
<title>Week 2 | CSIS 3600 | Spring 2018</title>
{% endblock %} {% block body %} {% load static %}
<div class="homework-container">
  <div class="title-container">
    <h2><i class="fal fa-book fa-xs"></i> Week 2</h2>
  </div>
  <div class="homework">
    <h3 class="no-margin-bottom"><i class="fal fa-pencil"></i> 1. Textbook problems Chapter 2</h3>
    <dl class="spanAll">
      <dt>Problem: 1</dt>
      <dd>There is no limit to the number of processes that can be in the ready and blocked states. At most, n processes may be in the run state, since a process in the run state must be allocated to a CPU, and there are only n CPUs.</dd>
      <dt>Problem: 2</dt>
      <dd>There can be zero processes in any of the three states. It is possible for all the processes to be blocked while waiting on I/O operations, leaving no processes in the ready and running states. All processes can be either in the ready or run state,
        leaving no processes blocked.</dd>
      <dt>Problem: 3</dt>
      <dd>It increases CPU utilization. While one process is blocked, waiting for I/O to complete, the CPU may execute another process.</dd>
      <dt>Problem: 6</dt>
      <dd>
        <ol type="a">
          <li>Possible, when a process’s time quantum expires</li>
          <li>Possible, when a process issues an I/O request</li>
          <li>Not possible, although process could first go to the blocked state, then the swapped-blocked</li>
          <li>Not possible, although process could first go to the ready state, then to the run state</li>
          <li>Possible, when a process terminates itself</li>
        </ol>
      </dd>
      <dt>Problem: 8</dt>
      <dd>Possible, when a process terminates itself</dd>
      <dt>Problem: 28d</dt>
      <dd><img class="round-robin-img" src="{% static 'img/week2/28d.jpg' %}" alt="Round Robin for 28 D"></dd>
      <dt>Problem: 28e</dt>
      <dd><img class="round-robin-img" src="{% static 'img/week2/28e.jpg' %}" alt="Round Robin for 28 E"></dd>
    </dl>
  </div>
  <div class="homework">
    <h3><i class="fal fa-pencil"></i> 2. List the Linux commands we covered today and what they do</h3>
    <ul>
      <li>
        <code>chown</code>
        <p>Change ownership of a file</p>
      </li>
      <li>
        <code>find</code>
        <p>Searches the directroy tree</p>
      </li>
      <li>
        <code>cp</code>
        <p>Copies Files</p>
      </li>
      <li>
        <code>vmstat</code>
        <p>Provides a snapshot of everything in a system</p>
      </li>
      <li>
        <code>df</code>
        <p>Reports filesystem disk space usage</p>
      </li>
      <li>
        <code>grep</code>
        <p>Used for searching one or more files</p>
      </li>
      <li>
        <code>cpio</code>
        <p>Back up empty directories</p>
      </li>
      <li>
        <code>alias</code>
        <p>Allows substitution of a small or more familiar name in place of a long string</p>
      </li>
    </ul>
    <ul>
      <li>
        <code>awk</code>
        <p>Searches for patterns in a file and processes them</p>
      </li>
      <li>
        <code>wc</code>
        <p>Counts words</p>
      </li>
      <li>
        <code>diff</code>
        <p>Shows the differences between files</p>
      </li>
      <li>
        <code>less</code>
        <p>Lest you scroll through files</p>
      </li>
      <li>
        <code>set</code>
        <p>Show all environment variables</p>
      </li>
      <li>
        <code>export</code>
        <p>Sets the value of a variable so it is visible to all sub-process that belong to the current shell</p>
      </li>
    </ul>
  </div>
  <div class="homework">
    <div class="spanAll">
      <h3><i class="fal fa-pencil"></i> 3. Add to the PATH variable so you can launch firefox inside the unix shell</h3>
      <ul>
        <li><code>export PATH=$PATH:/path/to/firefox</code></li>
      </ul>
    </div>
  </div>
  <div class="homework">
    <h3><i class="fal fa-pencil"></i> 4. Add chrome to your PATH variable and test it.</h3>
    <div class="spanAll">
      <ul>
        <li>
          <code>export PATH=$PATH:/path/to/chrome</code>
        </li>
      </ul>
    </div>
  </div>
  <div class="homework">
    <h3><i class="fal fa-pencil"></i> 5. Add an alias for Notepadd++. Call it notepad++</h3>
    <div class="spanAll">
      <ul>
        <li><code>alias notepad++='/path/to/notepadd++'</code></li>
      </ul>
    </div>
  </div>
  <div class="homework spanAll">
    <h3><i class="fal fa-pencil"></i> 6. Add the java jdk to your PATH variable.  Add the variable CLASSPATH.  Then compile and run a simple java program of your choice from the unix command line.</h3>
    <div class="spanAll">
      <ul>
        <li>
          <code>export PATH=$PATH:/Java/jdk1.7.0/bin</code>
        </li>
        <li>
          <code>javac ~/test.java</code>
        </li>
        <li>
          <code>java test</code>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

csis3600/secret/templates/secret/clue1.html
{% extends "base.html" %}
{% block title %}
  <title>Secret | CSIS 3600</title>
{% endblock %}
{% block body %}
<div class="homework-container">
  <div class="title-container">
    <h2><i class="fal fa-user-secret fa-lg fa-spin"></i> Congrats! <i class="fal fa-user-secret fa-lg fa-spin"></i></h2>
  </div>
  <h2>You found the secret page. <i class="fab fa-angellist"></i></h2>
  <p>Aren't you special</p>
</div>
{% endblock %}

csis3600/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge"> {% block title %}{% endblock %}

  <!-- BOOTSTRAP SUCKS -->
  <!-- DJANGO RULES -->

  <!--##############################################-->
  <!-- IF YOU ARE READING THIS, PLEASE GIVE ME 100% -->
  <!--##############################################-->

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Abel|Open+Sans" rel="stylesheet">

  <!-- FONT AWESOME 5 -->
  <script defer src="{% static 'js/fontawesome-all.min.js' %}"></script>

  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'css/dest/main.css' %}">

  <!-- don't go to /secret/ -->
</head>

<body>
  <div class="site-container">
    <header class="gray-container large-container header-grid">
      <div class="main-heading">
        <h1>CSIS 3600 <i class="fab fa-github-alt"></i></h1>
        <h2>Zach Christensen</h2>
      </div>
      <div class="skills">
        <i class="fab fa-html5 fa-2x" id="html"></i>
        <i class="fab fa-css3 fa-2x" id="css"></i>
        <i class="fab fa-js fa-2x" id="js"></i>
        <i class="fab fa-sass fa-2x" id="sass"></i>
        <i class="fab fa-gulp fa-4x" id="gulp"></i>
        <i class="fab fa-npm fa-2x" id="npm"></i>
        <i class="fab fa-python fa-2x" id="python"></i>
      </div>
    </header>
    <nav role="navigation">
      <ul>
        <li class="gray-container {% if request.path == '/weeklywork/week-1/' %}active{% endif %}"><a href="{% url 'weeklywork:week1' %}">Week 1</a></li>
        <li class="gray-container {% if request.path == '/weeklywork/week-2/' %}active{% endif %}"><a href="{% url 'weeklywork:week2' %}">Week 2</a></li>
        <li class="gray-container {% if request.path == '/weeklywork/week-3/' %}active{% endif %}"><a href="{% url 'weeklywork:week3' %}">Week 3</a></li>
        <li class="gray-container {% if request.path == '/weeklywork/week-4/' %}active{% endif %}"><a href="{% url 'weeklywork:week4' %}">Week 4</a></li>
        <li class="gray-container {% if request.path == '/weeklywork/week-5/' %}active{% endif %}"><a href="{% url 'weeklywork:week5' %}">Week 5</a></li>
        <li class="gray-container {% if request.path == '/weeklywork/week-6/' %}active{% endif %}"><a href="{% url 'weeklywork:week6' %}">Week 6</a></li>
        <li class="gray-container {% if request.path == '/weeklywork/week-7/' %}active{% endif %}"><a href="{% url 'weeklywork:week7' %}">Week 7</a></li>
        <li class="gray-container {% if request.path == '/weeklywork/week-8/' %}active{% endif %}"><a href="{% url 'weeklywork:week8' %}">Week 8</a></li>
        <li class="gray-container {% if request.path == '/weeklywork/week-12/' %}active{% endif %}"><a href="{% url 'weeklywork:week12' %}">Week 12</a></li>
        <li class="gray-container {% if request.path == '/weeklywork/week-13/' %}active{% endif %}"><a href="{% url 'weeklywork:week13' %}">Week 13</a></li>
        <li class="gray-container {% if request.path == '/contact/' %}active{% endif %}"><a href="{% url 'contact:contactForm' %}">Contact</a></li>
      </ul>
    </nav>
    {% block body %}{% endblock %}
  </div>

</body>

</html>